name: python3
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - scikit-learn==0.18.1
  - matplotlib
  - opencv==3.1
  - jupyter
  - notebook
  - pandas
  - keras
  - mkl-service
