name: python3
channels:
  - conda-forge
dependencies:
  - python==3.6
  - numpy==1.12
  - scipy==0.19.1
  - scikit-learn==0.18.1
  - matplotlib==2.2.2
  - opencv==3.1
  - jupyter==1.0
  - notebook==5.4.1
  - pandas==0.22
  - tensorflow==1.7.0
  - keras==2.1.5
  - mkl-service==1.1.2
